language:
  - python

dist:
  - xenial

python:
  - 3.7

install:
  - pip install pipenv
  - export PIPENV_VERBOSITY=-1
  - pipenv install --dev

script:
  - export BOTO_CONFIG=/dev/null
  - pipenv run python -m pytest
